name: glucose
channels:
  - defaults
dependencies:
  - python=3.10
  - xgboost
  - urllib3
  - matplotlib-inline
  - debugpy
  - xz
  - certifi
  - pygments
  - pyzmq
  - libgomp
  - pip
  - pexpect
  - executing
  - libffi
  - jedi
  - zeromq
  - ncurses
  - zlib
  - sqlite
  - _libgcc_mutex
  - ca-certificates
  - libgcc-ng
  - jupyter_client
  - wcwidth
  - jupyter_core
  - _openmp_mutex
  - libuuid
  - traitlets
  - openssl
  - python-dateutil
  - libsodium
  - ld_impl_linux-64
  - backcall
  - pickleshare
  - setuptools
  - ipython
  - pure_eval
  - six
  - tornado
  - tzdata
  - wheel
  - readline
  - parso
  - stack_data
  - libstdcxx-ng
  - decorator
  - nest-asyncio
  - asttokens
  - entrypoints
  - prompt-toolkit
  - bzip2
  - tk
  - ptyprocess
  - ipykernel
  - pytz
  - python-dotenv
